name: Metrics
on:
 # schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Vilagamer999
          template: classic
          base: header, activity, community, repositories #, metadata
          config_animations: yes
          config_timezone: Europe/Spain
          optimize: no
          use_prebuilt_image: yes

          #plugin_isocalendar: yes
          #plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_lines: yes
          
          #plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          #plugin_music: yes
          #plugin_music_mode: recent
          #plugin_music_provider: youtube
          
          #plugin_pagespeed: yes
          #plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          #plugin_pagespeed_url: https://vilagamer999.github.io/
